name: Update Attribute Dictionary JSON

on:
  # TODO: This will eventually become a daily cron job
  #   workflow_dispatch:
  #   schedule:
  #     - cron: '0 17 * * 2' # 9AM PST (5PM UTC) on Tuesday mornings
  pull_request:
    branches:
      - attribute-dictionary-json-action

env:
  BOT_NAME: nr-opensource-bot
  BOT_EMAIL: opensource+bot@newrelic.com

jobs:
  update-json:
    name: Update JSON
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install dependencies
        run: yarn install --frozen-lockfile
